### ISSUE TITLE
Co-authoring

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/pydocload#1]
Hi @StephenBrown2, @cs01,

I'm creating this repo to move the code of `mkdocstrings` responsible for loading the documentation.

Since you were contributors, I want to add you as co-authors on the first commit, following this method: https://stackoverflow.com/questions/7442112/how-to-attribute-a-single-commit-to-multiple-developers

I want to make sure you agree to it :slightly_smiling_face: 

You can react with a thumbs up if you do!

For the "why" I'm moving this part of the code, I'll explain it in the [Architecture](https://github.com/pawamoy/mkdocstrings/issues/28#issuecomment-582141157) issue :slightly_smiling_face:

**Comment by cs01** [comment]
IIUC this will be a library to generate documentation data in some structured format. Then other tools can depend on it and use that structured data to generate documentation with whatever kind of markup or formatting they want? If so, sounds cool.

**Comment by pawamoy** [comment]
That's the idea!
